apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        volumeMounts:
        - name: /data/
          mountPath: /config
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeDevices:
        - name: data
          devicePath: /data
      volumes:
      - name: /data/
        hostPath:
          path: /data/config
      - name: data
        persistentVolumeClaim:
          claimName: heimdall-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  type: LoadBalancer
  selector:
    app: heimdall
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc
  labels:
    app: heimdall
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
